### ISSUE TITLE
By option for Degree term

### ISSUE THREAD

**Issue by dth2** [statnet/tergmLite#18]
Hi Sam,
Martina mentioned that she brought up the degree_by issue during your MIDAS call and that this seemed like something that could be updated fairly easily so here is the official issue.

Thanks
-Deven  
 
The SHAMP project is trying to include a degree term with a by argument in the persistent network.  The model being implemented is:

fit.2$formation
~edges + nodecov("age") + nodecov("agesq") + nodefactor("race", 
    base = 5) + nodematch("race", diff = TRUE) + absdiff("sqrt.age.adj") + 
    nodefactor("sex.ident", base = 1:2) + degree(1, by = "sb") + 
    nodefactor("dsb.cohab", base = 1) + offset(nodematch("sex", 
    diff = FALSE))

Running a simulation using EpiModelHIV generates the following error from tergmLite.                      

Error in tergmLite::updateModelTermInputs(dat, network = 2) : 
  tergmLite does not know how to update the term degree_by_attr in the formation model formula
Called from: tergmLite::updateModelTermInputs(dat, network = 2)

A cursory look at the tergmLite code shows that degree_by_attr is not supported.  From line 59 of update.Model.terms

    supported.terms <- c("edges", "nodematch", "nodefactor",
                         "concurrent", "concurrent_by_attr", "degree",
                         "absdiff", "absdiffby", "nodecov", "nodemix",
                         "absdiffnodemix", "degrange")
    if (!(term$name %in% supported.terms)) {
      stop("tergmLite does not know how to update the term ",
           term$name," in the formation model formula") 

However, at line 269 there is code specifically defining arg for a by statement in the updateInputs_degree function  (byarg <- args$byarg).  So perhaps the functionality for degree by is already at least partially implemented or perhaps it is implemented but the term has just not been added to the list of supported terms?

**Comment by smjenness** [comment]
Sure thing, I can add support for degree by attr this week...

**Comment by martinamorris** [comment]
much appreciated @smjenness, and just a little nudge

**Comment by smjenness** [comment]
Closed in 97681c52889ed44cee3d5db98210c665087e139b

@dth2 and @martinamorris: updated as requested; please test and report if you have any problems
