### ISSUE TITLE
initialization of edge set for 800k node networks

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergmLite#29]
Starting this in `tergmLite` but feel free to move it elsewhere if you want to.

Recent revelations about suboptimal starting points leading to long runtimes led me to wonder how the initial set of edges was chosen in the 800k node networks used for simulation.  It sounds like 750k people are "birthed" in on the first time step (the other 50k being leftovers from the estimation run), and the requisite edges come from a (very) long MCMC burnin.

@dth2 do you think the need to add all these edges is the biggest factor requiring the long burnin, or are there other factors that are just as big? (if so, which ones?) i.e., if we had a reasonable edge set to start with, do you think we could cut down appreciably on the burnin runtime?

In principle it seems like `san` could be used to populate the initial edge set.  A hypothetical workflow consistent with the various constraints we operate under might look like the following:

- obtain target stats for 800k ppop size (e.g., from ergm.ego) for each of the three networks, and obtain a single 800k node pseudopopulation (represented in a lite format)
- run `san` with this pseudopopulation and the cohab target stats (and constraints) to get the cohab edges
- add a vertex attribute indicating which nodes have ties in the cohab network
- run `san` for the other two networks with their respective target stats and constraints, using the same pseudopopulation that the cohab model used (starting with zero edges of course, and with the additional vertex attribute indicating ties in the cohab network)
- start simulation from the three `san` networks (which all have the same underlying node set)

It's hard to know how big a difference this would make, but optimistically it would be better than starting with only 1/16th of the nodes possibly having any edges, especially if the need to get a reasonable edge set is a driving factor behind the long burnin.  I also think it's a little more systematized than what we're doing now, and could probably be generalized to other contexts relatively easily.

Getting this to work seamlessly with `ergm`'s top-level `san` functions would probably require expanding the `networkLite` class.  (It might be possible to call `san`'s C code directly, but that wouldn't be in the best interest of long-term stability.)

**Comment by chad-klumb** [comment]
This is not really a `tergmLite` issue so I'm closing it.

Initializing multi-network models with cross-network effects can be accomplished via `san`.  Assuming two networks with bi-directional cross-network effects, in order for the initialization to be close on all target stats it can be helpful to include an additional statistic in the second network's `san` run that corresponds to the first network's cross-network statistic.  This may not be necessary in all cases, but has proven very useful in the SHAMP work, where it allows one to get within a small fraction of all the targets for both the cohab and pers networks (which is not easy to do with either `ergm` or `tergm` simulation).

**Comment by martinamorris** [comment]
I'm going to transfer this issue over to our cross-project repo.
