### ISSUE TITLE
Question on circular dependencies before CRAN submission

### ISSUE THREAD

**Issue by smjenness** [statnet/tergmLite#32]
@chad-klumb @krivit : Could you please comment on this.
cc: @martinamorris 

I am just about ready to submit tergmLite to CRAN, but I am concerned about whether we should keep EpiModel as a `Suggest` in the DESCRIPTION file because this may create a circular dependency when I then update EpiModel to `Depend` on tergmLite. EpiModel is currently a `Suggest` for tergmLite only so it can run unit tests that depend on the combined functionality of tergmLite and EpiModel (tergmLite is otherwise independent of EpiModel). Another alternative is to remove all the EpiModel-related unit terms from tergmLite and put them in EpiModel, but I think it is probably better practice to test tergmLite builds independently. Thoughts?

**Comment by chad-klumb** [comment]
I think it's okay to have depend one way and suggest the other, e.g. tergm and ergm do that.

Apparently Pavel was wondering the same thing 7 years ago:

https://r.789695.n4.nabble.com/Submitting-packages-with-weak-circular-dependencies-to-CRAN-td4660766.html

so he can probably give more definitive advice.
