### ISSUE TITLE
tergmLite-private?

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergmLite#35]
Updates to tergmLite to work with (t)ergm 4.0 will necessarily reference the latter which are currently private.  Should we make a tergmLite-private@dev branch to hold these updates?

**Comment by martinamorris** [comment]
that seems like a good idea, now that we have a CRAN release.  @smjenness?

**Comment by smjenness** [comment]
That's fine with me

**Comment by chad-klumb** [comment]
This should be up now (statnet/tergmLite-private).  If there are any concerns let me know.
