### ISSUE TITLE
removing stergm_prep and ergm_prep from exports

### ISSUE THREAD

**Issue by dth2** [statnet/tergmLite#36]
Hi Sam,
Both the ergm_prep and stergm_prep initialization functions have been removed from exports and made internal to init_tergmLite.  However, when I use init_tergmLite rather than stergm_prep directly I get an error (shown below).  This code worked fine this using the _prep calls directly before I updated tergmLite.  Is there any reason that we should not be able to call these functions directly, particularly since so much of our code is already written to use these functions

netsim(est, param, init, control)
Error in tergmLite::init_tergmLite(nw[[i]], x[[i]]$formation, x[[i]]$coef.diss$dissolution,  : 
  unused arguments (x[[i]]$formation, x[[i]]$coef.diss$dissolution, x[[i]]$coef.form, x[[i]]$coef.diss$coef.adj, x[[i]]$constraints)

**Comment by DamienGeorges** [comment]
Hi Sam, Hi Deven,

I have the same issue. 
My quick fix (not ideal) is to stick to v1.2.0  of tergmLite (`remotes::install_github("statnet/tergmLite@v1.2.0")`)
This version seems still work smoothly with EpiModel package suits.

Best,
Damien

**Comment by dth2** [comment]
Thanks Damien.  An alternative that I am currently using is to move the functions in to the EpiModelHIV utilities, but also not idea.

**Comment by smjenness** [comment]
I'm sorry that you are both encountering this issue. I have had to update tergmLite in this way in advance of publishing it on CRAN, which should be coming soon. You can certainly use the prior version (v.2.0 is fine and takes advantage of the new networkLite API) but if you send me a link to your code where you have input init_tergmLite I can help debug. Thanks

**Comment by DamienGeorges** [comment]
As a follow up on that point.

@dth2 method (source the 'old' version of `stergm_prep` and `ergm_prep`) is so far the best/easiest way to handle this issue (thanks Deven)

A more elegent way would be to use the new `init_tergmLite` function. The issue so far is that it does not support multi network approach as implemented in EpiModelHIV framework.

In multi-network simulation we do not want to replicate the other attributes such as `param`, `control`, `attr`, ... but only initiate a tergmLite version of the `netest` objects. 

An easy fix would be to add a argument such as `netest.only` (delfault = `FALSE`) in `init_tergmLite` but this would implies not to return the full EpiModel object but only the network converted in `tergmLite` flavor which might be confusing to explain in the help file..

Another would be to add  `stergm_prep` and `ergm_prep` in `tergmLite` (not exported) and to call the function within `init_tergmLite` for the network convertion. This way developpers can access the  `stergm_prep` and `ergm_prep` functions using the `:::` accessor.  

Do you see another elegent way to handle this issue?

I can add such an argument to the function and comit it on the current tergmLite branch if you think it is worthy.

Best,
Damien

**Comment by smjenness** [comment]
> In multi-network simulation we do not want to replicate the other attributes such as param, control, attr, ... but only initiate a tergmLite version of the netest objects.

Hi @DamienGeorges : I'm not quite clear what you mean here. The tergmLite approach now (in the version released on CRAN) supports the multi-network setup, like in EpiModelHIV, but does not replicate the other model components. I'm happy to help you convert over to this now public, stable version of tergmLite.
