### ISSUE TITLE
Update get_vertex_attributes

### ISSUE THREAD

**Issue by adam-s-elder** [statnet/tergmLite#45]
It looks like the get_vertex_attributes has some copied code from set_vertex_attributes that needs to be changed. I would submit the changes myself, but I was looking at the documentation because I don't know what get_vertex_attributes does. 

https://github.com/statnet/tergmLite/blob/e3dada01b3bdceba07ed658bc0547964a1b8dc7d/man/get_vertex_attribute.Rd#L22-L29

**Comment by smjenness** [comment]
@adam-s-elder : docs fixed in above commit. Let me know if that addresses your question. If so, please close the issue.

**Comment by adam-s-elder** [comment]
Thanks.  I will need to figure out what query means, but I am guessing this fixes the issue.
