### ISSUE TITLE
Issues in long EpiModel runs

### ISSUE THREAD

**Issue by adam-s-elder** [statnet/tergmLite#46]
I am currently running a fairly long epimodel simulation.  This is my current install stack:

```r
remotes::install_github(c("statnet/rle@master",
"statnet/statnet.common@master",
"statnet/network@master",
"statnet/networkDynamic@master",
"statnet/ergm-private@dev",
"statnet/ergm.multi-private@dev",
"statnet/tergm-private@dev",
"statnet/tergmLite-private@dev",
"statnet/EpiModel@summary_statistics"#,
"statnet/EpiModelHIV-p@whamp-4.0"
), force = TRUE, dependencies = FALSE)
```

After running for about 300 steps, there is pretty sizable slowdown (steps in the epimodel simulation that took about 2 seconds in the beginning take about a minute).  After about 20-50 more steps, the simulation fails and provides this error:

```r
Error: vector memory exhausted (limit reached?)
```

Here is the traceback I am getting:

```
8: matrix(ext.state$lasttoggle, ncol = 3)
7: trm$ext.decode(object$ext.state[[i]], object$el, object$nw0)
6: .reconcile_ergm_state(object)
5: update.ergm_state_full(z$state)
4: update(z$state)
3: tergm_MCMC_slave(state, ergm.eta(coef, state$model$etamap), control, 
       verbose = FALSE)
2: tergmLite::simulate_network(state = dat$p[[2]]$state, coef = c(nwparam.p$coef.form, 
       nwparam.p$coef.diss$coef.adj), control = dat$control$MCMC_control[[2]], 
       save.changes = TRUE) at mod.simnet.R#59
1: simnet_msm(old_dat, at)
```

It appears that inside of .reconcile_ergm_state there is a for loop :

```r
if (object$ext.flag == ERGM_STATE_C_CHANGED) {
    for (i in seq_along(object$model$terms)) {
      trm <- object$model$terms[[i]]
      if (is.null(trm$ext.decode)) 
        next
      o <- trm$ext.decode(object$ext.state[[i]], object$el, 
        object$nw0)
      object$el <- o$el
      object$nw0 <- o$nw0
    }
```

where some sort of decoding occurs.  the model term that causes the error is last toggle:

```r
Browse[7]> trm
$name
[1] "_lasttoggle"

$coef.names
NULL

$duration
[1] TRUE

$dependence
[1] FALSE

$ext.encode
function (el, nw0) 
list(time = as.integer(NVL(nw0 %n% "time", 0)), lasttoggle = as.integer(nw0 %n% 
    "lasttoggle"))
<bytecode: 0x7ff4ed2e3270>
<environment: 0x7ff14b2d77c0>

$ext.decode
function (ext.state, el, nw0) 
{
    nw0 %n% "time" <- ext.state$time
    nw0 %n% "lasttoggle" <- matrix(ext.state$lasttoggle, ncol = 3)
    list(el = el, nw0 = nw0)
}
<bytecode: 0x7ff4ed2e2c88>
<environment: 0x7ff14b2d77c0>

$pkgname
[1] "tergm"

$inputs
numeric(0)

$iinputs
integer(0)

attr(,"aux.slots")
[1] 3
```

The line in which the failure happens is this one:

```r
nw0 %n% "lasttoggle" <- matrix(ext.state$lasttoggle, ncol = 3)
```

If I try to dive further into the "%n%" function, trying to step into

```r
.Internal(matrix(data, nrow, ncol, byrow, dimnames, missing(nrow), 
    missing(ncol)))
```
fails and the error occurs (I don't really understand .Internal, so maybe this is expected).

My hope with this initial post is to find out if there is a simple explanation for the error I am seeing.  If this is not the case, I will provide you with a reproducible example (I will capture the state of the dat object right before the failure occurs).

Thanks for your help.  I am tagging @martinamorris to keep her in the loop.

**Comment by chad-klumb** [comment]
It would help to know if some part of the `dat` object has grown quite large; if so that could help pin down where the issue is.

**Comment by chad-klumb** [comment]
btw this may be better in `tergmLite-private` since that's the version being used

**Comment by adam-s-elder** [comment]
Good point.  I will follow up with an answer to your question in the termLite-Private github
