### ISSUE TITLE
consider disbanding the tergmLite package

### ISSUE THREAD

**Issue by chad-klumb** [statnet/tergmLite#52]
Assuming #51 pans out (and I think it should, with at most some minor tweaks to `ergm` and `tergm` `simulate` functions), the functionality offered by the `tergmLite` package would basically consist of:

- `init_tergmLite` in `initialize.R`
- a few lines of `network` wrappers in `network.R`
- a few lines of `simulate` wrappers in `simulate.R`
- a few lines of network updating logic in `update.R` and associated `C` code
- the `networkLite` class definition in `util.R`

Despite the name, `init_tergmLite` should really be in `EpiModel`; it assumes things about the `dat` object and the `control.net` control class, and those are `EpiModel` constructs.  (Post-#51 it may also be a shorter function than it is now.)

Interest has been expressed in using `networkLite`s in lower-level `statnet` packages, and this would mean moving the class definition to another package (at the level of `ergm` or below).

The other few lines of code could quite reasonably go in `EpiModel` since that is where they are typically used.

The main advantage of disbanding `tergmLite` would be one less package to maintain.  (The `networkLite` move could in principle happen even if `tergmLite` were kept around, although given that `init_tergmLite` *should* be moved to `EpiModel`, that would leave no more than ~100 lines of code in `tergmLite`.)

**Comment by smjenness** [comment]
That's great @chad-klumb! That was our (me and @martinamorris's at least) original vision. I would fully support that and have the remaining bits of tergmLite code migrate to EpiModel.

**Comment by martinamorris** [comment]
Amen to that.

**Comment by smjenness** [comment]
This has been completed. All tergmLite functionality wrapped into EpiModel.
